name: ansicolor
version: 2.0.3
description: >-
  Looking to add some color to your terminal logs? `ansicolor` is an xterm-256
  color support library that lets you change the foreground and background
  color of your text.
repository: https://github.com/google/ansicolor-dart
environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.8
topics:
  - cli
